name: Mise à jour calendrier PRO D2

on:
  workflow_dispatch:

  schedule:
    # Jeudi
    - cron: "40 16 * * 4"
      timezone: "Europe/Paris"
    - cron: "12 17 * * 4"
      timezone: "Europe/Paris"
    - cron: "10 18 * * 4"
      timezone: "Europe/Paris"
    - cron: "00 19 * * 4"
      timezone: "Europe/Paris"

    # Vendredi
    - cron: "30 19 * * 5"
      timezone: "Europe/Paris"
    - cron: "00 20 * * 5"
      timezone: "Europe/Paris"
    - cron: "30 20 * * 5"
      timezone: "Europe/Paris"
    - cron: "00 21 * * 5"
      timezone: "Europe/Paris"
    - cron: "00 23 * * 5"
      timezone: "Europe/Paris"

permissions:
  contents: write

jobs:
  update-classement:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du dépôt
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installation de Playwright
        run: |
          pip install playwright
          playwright install --with-deps chromium

      - name: Récupération du classement
        run: |
          python scraper.py

      - name: Enregistrement du classement
        run: |
          git config user.name "Twelve Prono Bot"
          git config user.email "actions@github.com"

          git add classement.json debug_classement.txt

          if git diff --cached --quiet
          then
            echo "Aucune modification du classement."
          else
            git commit -m "Mise à jour automatique du classement"
            git push
          fi
