name: Mise à jour classement PRO D2

on:
  workflow_dispatch:

  schedule:
  # Jeudi
  - cron: "10 18 * * 4"  # Jeudi 23h20 France
  - cron: "40 18 * * 4"  # Jeudi 23h40 France

  # Vendredi
  - cron: "00 16 * * 5" # Vendredi 19h France
  - cron: "00 17 * * 5"  # Vendredi 20h40 France
  - cron: "00 18 * * 5"  # Vendredi 21h30 France
  - cron: "30 18 * * 5"  # Vendredi 23h30 France

   # SamediTEST
  - cron: "00 16 * * 6" # Vendredi 18h France
  - cron: "00 17 * * 6"  # Vendredi 19h France
  - cron: "00 18 * * 6"  # Vendredi 20h France
  - cron: "30 20 * * 6"  # Vendredi 22h30  

permissions:
  contents: write

jobs:
  update-classement:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du dépôt
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installation de Playwright
        run: |
          pip install playwright
          playwright install --with-deps chromium

      - name: Récupération du classement
        run: |
          python scraper.py

      - name: Enregistrement du classement
        run: |
          git config user.name "Twelve Prono Bot"
          git config user.email "actions@github.com"

          git add classement.json debug_classement.txt

          if git diff --cached --quiet
          then
            echo "Aucune modification du classement."
          else
            git commit -m "Mise à jour automatique du classement"
            git push
          fi
